INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, CREATE_DATE)
VALUES (200, 'Customer_First_200', 'Customer_Last_200', CURRENT_TIMESTAMP);
INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, CREATE_DATE)
VALUES (201, 'Customer_First_201', 'Customer_Last_201', CURRENT_TIMESTAMP);

INSERT INTO TRANSACTION (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, CREATE_DATE)
VALUES (1, 200, 2000.00, CURRENT_TIMESTAMP);
INSERT INTO TRANSACTION (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, CREATE_DATE)
VALUES (2, 201, 300.42, CURRENT_TIMESTAMP);
INSERT INTO TRANSACTION (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, CREATE_DATE)
VALUES (3, 200, 77.01, CURRENT_TIMESTAMP);
INSERT INTO TRANSACTION (TRANSACTION_ID, CUSTOMER_ID, AMOUNT, CREATE_DATE)
VALUES (4, 200, 17.99, CURRENT_TIMESTAMP);